export const DEFAULT_REPORT_DATA = {
  labConfig: {
    name: 'SUNRISE',
    subtitle: 'Diagnostic & Research Centre (Demo)',
    address: '[Your Lab Address Here]',
    mobile: '0000000000',
    landline: '000-0000000',
    logoUrl: '/logo.png',
    showSideBadge: true,
    sideBadgeText: 'TEST REPORT',
  },
  patient: {
    id: '11111111-1111-1111-1111-111111110001',
    title: 'Mr.',
    full_name: 'RAHUL DEMO',
    uhid: 'DEMO.0000000001',
    age_years: 40,
    age_months: 0,
    age_days: 0,
    gender: 'M',
    phone: '9000000001',
  },
  visit: {
    id: '22222222-2222-2222-2222-222222220001',
    visit_code: 'DEMO000001',
    ref_doctor: 'Dr. SAMPLE REFERRER',
    client_name: 'SAMPLE CLINIC',
    client_code: '0001',
    rch_id_mcts_id: '',
    sample_type: 'FLOURIDE PLASMA (R)',
    collected_at: '01/Jan/2026 09:00AM',
    reported_at: '01/Jan/2026 11:00AM',
    status: 'Final Report',
  },
  department: 'DEPARTMENT OF BIOCHEMISTRY',
  testResults: [
    {
      id: 'test-1',
      test_name: 'Plasma Glucose-Random',
      result_value: '114',
      unit: 'mg/dl',
      reference_range: '60-140',
      method: 'Glucose Oxidase/Peroxidase',
      flag: 'NORMAL',
    },
  ],
  interpretation: {
    enabled: true,
    increasedIn: [
      'Diabetes Mellitus',
      'Stress (e.g., emotion, burns, shock, anesthesia)',
      'Acute pancreatitis',
      'Chronic pancreatitis',
      'Wernicke encephalopathy (vitamin B1 deficiency)',
      'Effect of drugs (e.g. corticosteroids, estrogens, alcohol, phenytoin, thiazides)',
    ],
    decreasedIn: [
      'Pancreatic disorders',
      'Extrapancreatic tumors',
      'Endocrine disorders',
      'Malnutrition',
      'Hypothalamic lesions',
      'Alcoholism',
    ],
    disclaimer:
      'Note : Test result can vary as per the timing of sample collection, duration of fasting, timing between collection and testing, timing of meal and type of diet taken, medication, physical activity before collection of sample etc. Test results needs to be correlated clinically.',
  },
  signatory: {
    name: 'Dr. SAMPLE SIGNATORY',
    qualifications: 'MBBS, MD [Path]',
    reg_no: 'Reg. No. - 00000',
  },
  barcode_value: 'DEMO0000001',
  qr_token: '0000000000000000000000000000000000000000000000000000000000001',
};

export const CBC_PRESET = {
  ...DEFAULT_REPORT_DATA,
  patient: {
    id: '11111111-1111-1111-1111-111111110002',
    title: 'Mrs.',
    full_name: 'PRIYA DEMO',
    uhid: 'DEMO.0000000002',
    age_years: 35,
    age_months: 0,
    age_days: 0,
    gender: 'F',
    phone: '9000000002',
  },
  visit: {
    ...DEFAULT_REPORT_DATA.visit,
    id: '22222222-2222-2222-2222-222222220002',
    visit_code: 'DEMO000002',
    ref_doctor: 'Dr. SAMPLE REFERRER TWO',
    client_name: 'SAMPLE CLINIC TWO',
    client_code: '0002',
    sample_type: 'EDTA WHOLE BLOOD',
    collected_at: '02/Jan/2026 09:00AM',
    reported_at: '02/Jan/2026 11:00AM',
  },
  department: 'DEPARTMENT OF HEMATOLOGY',
  testResults: [
    { id: 'cbc-1', test_name: 'Hemoglobin (Hb)', result_value: '13.5', unit: 'g/dL', reference_range: '12.0 - 15.5', method: 'Cyanmethemoglobin', flag: 'NORMAL' },
    { id: 'cbc-2', test_name: 'Total Leukocyte Count (TLC)', result_value: '7,200', unit: '/cumm', reference_range: '4,000 - 11,000', method: 'Automated Cell Counter', flag: 'NORMAL' },
    { id: 'cbc-3', test_name: 'Platelet Count', result_value: '2.8', unit: 'Lakhs/cumm', reference_range: '1.5 - 4.5', method: 'Electrical Impedance', flag: 'NORMAL' },
    { id: 'cbc-4', test_name: 'Packed Cell Volume (PCV)', result_value: '41.2', unit: '%', reference_range: '36.0 - 46.0', method: 'Calculated', flag: 'NORMAL' },
    { id: 'cbc-5', test_name: 'Neutrophils', result_value: '62', unit: '%', reference_range: '40 - 75', method: 'Differential Counter', flag: 'NORMAL' },
    { id: 'cbc-6', test_name: 'Lymphocytes', result_value: '30', unit: '%', reference_range: '20 - 45', method: 'Differential Counter', flag: 'NORMAL' },
    { id: 'cbc-7', test_name: 'Eosinophils', result_value: '5', unit: '%', reference_range: '1 - 6', method: 'Differential Counter', flag: 'NORMAL' },
    { id: 'cbc-8', test_name: 'Monocytes', result_value: '3', unit: '%', reference_range: '2 - 8', method: 'Differential Counter', flag: 'NORMAL' },
  ],
  barcode_value: 'DEMO0000002',
  qr_token: '0000000000000000000000000000000000000000000000000000000000002',
  interpretation: {
    enabled: true,
    increasedIn: [],
    decreasedIn: [],
    disclaimer: 'Note: Results must be correlated with clinical presentation. Automated hemogram verified microscopically.',
  },
};

export const LIPID_PRESET = {
  ...DEFAULT_REPORT_DATA,
  patient: {
    id: '11111111-1111-1111-1111-111111110003',
    title: 'Mr.',
    full_name: 'AMIT DEMO',
    uhid: 'DEMO.0000000003',
    age_years: 55,
    age_months: 0,
    age_days: 0,
    gender: 'M',
    phone: '9000000003',
  },
  visit: {
    ...DEFAULT_REPORT_DATA.visit,
    id: '22222222-2222-2222-2222-222222220003',
    visit_code: 'DEMO000003',
    ref_doctor: 'Dr. SAMPLE REFERRER THREE',
    client_name: 'SAMPLE CLINIC THREE',
    client_code: '0003',
    sample_type: 'SERUM',
    collected_at: '03/Jan/2026 09:00AM',
    reported_at: '03/Jan/2026 11:00AM',
  },
  department: 'DEPARTMENT OF BIOCHEMISTRY',
  testResults: [
    { id: 'lp-1', test_name: 'Serum Cholesterol - Total', result_value: '228', unit: 'mg/dL', reference_range: '< 200', method: 'CHOD-PAP Enzymatic', flag: 'HIGH' },
    { id: 'lp-2', test_name: 'Serum Triglycerides', result_value: '185', unit: 'mg/dL', reference_range: '< 150', method: 'GPO-PAP Enzymatic', flag: 'HIGH' },
    { id: 'lp-3', test_name: 'HDL Cholesterol (Good)', result_value: '38', unit: 'mg/dL', reference_range: '> 40', method: 'Direct Immunoinhibition', flag: 'LOW' },
    { id: 'lp-4', test_name: 'LDL Cholesterol (Bad)', result_value: '153', unit: 'mg/dL', reference_range: '< 100', method: 'Calculated (Friedewald)', flag: 'HIGH' },
    { id: 'lp-5', test_name: 'Cholesterol / HDL Ratio', result_value: '6.0', unit: 'Ratio', reference_range: '< 4.5', method: 'Calculated', flag: 'HIGH' },
  ],
  barcode_value: 'DEMO0000003',
  qr_token: '0000000000000000000000000000000000000000000000000000000000003',
  interpretation: {
    enabled: true,
    increasedIn: [
      'Primary Hypercholesterolemia, Atherosclerosis, Coronary Artery Disease',
      'Hypothyroidism, Nephrotic Syndrome, Obstructive Jaundice',
    ],
    decreasedIn: ['Malnutrition, Hyperthyroidism, Severe Chronic Liver Disease'],
    disclaimer: 'Patient fasted for 12 hours prior to specimen collection. Values interpreted according to NCEP ATP III clinical guidelines.',
  },
};

export const LFT_PRESET = {
  ...DEFAULT_REPORT_DATA,
  patient: {
    id: '11111111-1111-1111-1111-111111110004',
    title: 'Master',
    full_name: 'KIDS DEMO',
    uhid: 'DEMO.0000000004',
    age_years: 4,
    age_months: 6,
    age_days: 12,
    gender: 'M',
    phone: '9000000004',
  },
  visit: {
    ...DEFAULT_REPORT_DATA.visit,
    id: '22222222-2222-2222-2222-222222220004',
    visit_code: 'DEMO000004',
    ref_doctor: 'Dr. SAMPLE PEDIATRICIAN',
    client_name: 'SAMPLE CHILD CLINIC',
    client_code: '0004',
    rch_id_mcts_id: '',
    sample_type: 'SERUM',
    collected_at: '04/Jan/2026 09:00AM',
    reported_at: '04/Jan/2026 11:00AM',
  },
  department: 'DEPARTMENT OF BIOCHEMISTRY',
  testResults: [
    { id: 'lft-1', test_name: 'Bilirubin - Total', result_value: '0.6', unit: 'mg/dL', reference_range: '0.2 - 1.2', method: 'Diazo Method', flag: 'NORMAL' },
    { id: 'lft-2', test_name: 'Bilirubin - Direct', result_value: '0.18', unit: 'mg/dL', reference_range: '< 0.3', method: 'Diazo Method', flag: 'NORMAL' },
    { id: 'lft-3', test_name: 'SGOT / AST', result_value: '32', unit: 'U/L', reference_range: '10 - 40', method: 'UV Kinetic (IFCC)', flag: 'NORMAL' },
    { id: 'lft-4', test_name: 'SGPT / ALT', result_value: '26', unit: 'U/L', reference_range: '10 - 45', method: 'UV Kinetic (IFCC)', flag: 'NORMAL' },
    { id: 'lft-5', test_name: 'Alkaline Phosphatase (ALP)', result_value: '210', unit: 'U/L', reference_range: '100 - 350 (Pediatric)', method: 'p-NPP Kinetic', flag: 'NORMAL' },
    { id: 'lft-6', test_name: 'Total Protein', result_value: '7.1', unit: 'g/dL', reference_range: '6.0 - 8.0', method: 'Biuret', flag: 'NORMAL' },
    { id: 'lft-7', test_name: 'Serum Albumin', result_value: '4.4', unit: 'g/dL', reference_range: '3.5 - 5.2', method: 'BCG Dye Binding', flag: 'NORMAL' },
  ],
  barcode_value: 'DEMO0000005',
  qr_token: '0000000000000000000000000000000000000000000000000000000000004',
  interpretation: {
    enabled: true,
    increasedIn: ['Viral Hepatitis, Toxic Hepatitis, Biliary Obstruction'],
    decreasedIn: ['Chronic Liver Disease, Malabsorption'],
    disclaimer: 'Pediatric liver enzymes within age-appropriate physiological limits.',
  },
};

export const THYROID_PRESET = {
  ...DEFAULT_REPORT_DATA,
  patient: {
    id: '11111111-1111-1111-1111-111111110005',
    title: 'Ms.',
    full_name: 'NEHA DEMO',
    uhid: 'DEMO.0000000005',
    age_years: 29,
    age_months: 0,
    age_days: 0,
    gender: 'F',
    phone: '9000000005',
  },
  visit: {
    ...DEFAULT_REPORT_DATA.visit,
    id: '22222222-2222-2222-2222-222222220005',
    visit_code: 'DEMO000005',
    ref_doctor: 'Dr. SAMPLE REFERRER FIVE',
    client_name: 'SAMPLE WELLNESS CLINIC',
    client_code: '0005',
    sample_type: 'SERUM',
    collected_at: '05/Jan/2026 09:00AM',
    reported_at: '05/Jan/2026 11:00AM',
  },
  department: 'DEPARTMENT OF ENDOCRINOLOGY',
  testResults: [
    { id: 'tft-1', test_name: 'Triiodothyronine (Total T3)', result_value: '1.24', unit: 'ng/mL', reference_range: '0.80 - 2.00', method: 'CLIA', flag: 'NORMAL' },
    { id: 'tft-2', test_name: 'Thyroxine (Total T4)', result_value: '8.6', unit: 'ug/dL', reference_range: '5.1 - 14.1', method: 'CLIA', flag: 'NORMAL' },
    { id: 'tft-3', test_name: 'TSH (Ultrasensitive)', result_value: '2.15', unit: 'uIU/mL', reference_range: '0.27 - 4.20', method: 'ECLIA', flag: 'NORMAL' },
  ],
  barcode_value: 'DEMO0000006',
  qr_token: '0000000000000000000000000000000000000000000000000000000000005',
  interpretation: {
    enabled: true,
    increasedIn: ['Primary Hypothyroidism (TSH elevated)', 'Graves Disease / Hyperthyroidism (T3/T4 elevated)'],
    decreasedIn: ['Hyperthyroidism (TSH suppressed)', 'Secondary Hypothyroidism'],
    disclaimer: 'Euthyroid state. Circulating hormone levels are within physiological reference intervals.',
  },
};

export const KFT_PRESET = {
  ...DEFAULT_REPORT_DATA,
  visit: {
    ...DEFAULT_REPORT_DATA.visit,
    sample_type: 'SERUM',
  },
  department: 'DEPARTMENT OF BIOCHEMISTRY',
  testResults: [
    { id: 'kft-1', test_name: 'Blood Urea', result_value: '28.4', unit: 'mg/dL', reference_range: '15.0 - 45.0', method: 'GLDH Kinetic', flag: 'NORMAL' },
    { id: 'kft-2', test_name: 'Serum Creatinine', result_value: '0.9', unit: 'mg/dL', reference_range: '0.7 - 1.3', method: 'Modified Jaffe Kinetic', flag: 'NORMAL' },
    { id: 'kft-3', test_name: 'Serum Uric Acid', result_value: '5.4', unit: 'mg/dL', reference_range: '3.5 - 7.2', method: 'Uricase Enzymatic', flag: 'NORMAL' },
    { id: 'kft-4', test_name: 'Blood Urea Nitrogen (BUN)', result_value: '13.2', unit: 'mg/dL', reference_range: '7.0 - 20.0', method: 'Calculated', flag: 'NORMAL' },
  ],
  interpretation: {
    enabled: true,
    increasedIn: ['Prerenal azotemia, Glomerulonephritis, Renal failure, Dehydration'],
    decreasedIn: ['Low protein diet, Severe liver disease'],
    disclaimer: 'Renal parameters within normal physiological limits.',
  },
};

export const DEMO_PRESETS = [
  { label: 'Mr. RAHUL DEMO (Glucose)', preset: DEFAULT_REPORT_DATA, dept: 'Biochemistry' },
  { label: 'Mrs. PRIYA DEMO (CBC)', preset: CBC_PRESET, dept: 'Hematology' },
  { label: 'Mr. AMIT DEMO (Lipid Profile)', preset: LIPID_PRESET, dept: 'Biochemistry' },
  { label: 'Master KIDS DEMO (Pediatric LFT)', preset: LFT_PRESET, dept: 'Biochemistry' },
  { label: 'Ms. NEHA DEMO (Thyroid TFT)', preset: THYROID_PRESET, dept: 'Endocrinology' },
  { label: 'Kidney Function Test (KFT)', preset: KFT_PRESET, dept: 'Biochemistry' },
];
